### ISSUE TITLE
URLs should not be (fully) downcased

### ISSUE THREAD

**Issue by jaimeiniesta** [suddenrushofsushi/url_tincture#2]
Hello, just a quick note that URLs are case-sensitive:

https://www.w3.org/TR/WD-html40-970708/htmlweb.html

> URLs in general are case-sensitive (with the exception of machine names). There may be URLs, or parts of URLs, where case doesn't matter, but identifying these may not be easy. Users should always consider that URLs are case-sensitive.

The only part of the URL that is safe to downcase is the domain name, but after that, depending on what web server is running there, it might be case sensitive.

**Comment by suddenrushofsushi** [comment]
I agree, however for the purposes of this tool we're assuming there won't be multiple URLs with differing case matching a common pattern (rather, we don't need to know). If you need this to properly adhere to case-sensitivity, I'm open to adding an option to preserve case.

**Comment by jaimeiniesta** [comment]
Thanks, I didn't send a PR because I finally ended up using another library. Here's the PR where this issue was fixed there:

https://github.com/johnotander/normalize_url/pull/14
